services:
  cpdlc-server:
    image: cpdlc-server
    build:
      context: .
      dockerfile: source/CPDLCServer/Dockerfile
    env_file:
      - .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5272:8080"
