services:
  cpdlc-server:
    image: cpdlc-server
    build:
      context: .
      dockerfile: source/CPDLCServer/Dockerfile
    env_file:
      - .env
    ports:
      - "5272:8080"

  ngrok:
    profile: ngrok
    image: ngrok/ngrok:latest
    command:
      - "http"
      - "http://host.docker.internal:5272"
    env_file:
      - .env
    ports:
      - 4040:4040
