services:
  docs:
    build:
      context: docs/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  server:
    build:
      context: .
      dockerfile: source/CPDLCServer/Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"

  ngrok:
    profiles: [ngrok]
    image: ngrok/ngrok:latest
    command:
      - "http"
      - "http://host.docker.internal:5272"
    env_file:
      - .env
    ports:
      - 4040:4040
