<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
        <StaticWebAssetsEnabled>false</StaticWebAssetsEnabled>
    </PropertyGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="CPDLCServer.Tests" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="DotNetEnv" Version="3.1.1" />
        <PackageReference Include="MediatR" Version="12.5.0" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.0"/>
        <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.2.0" />
        <PackageReference Include="Microsoft.AspNetCore.SignalR.Common" Version="10.0.1" />
        <PackageReference Include="Microsoft.AspNetCore.SignalR.Protocols.Json" Version="10.0.1" />
        <PackageReference Include="Microsoft.AspNetCore.SignalR.Protocols.NewtonsoftJson" Version="10.0.1" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.0">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
        <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\CPDLCServer.Contracts\CPDLCServer.Contracts.csproj" />
    </ItemGroup>

    <ItemGroup>
      <AdditionalFiles Include="Pages\Atsu\Index.cshtml" />
      <AdditionalFiles Include="Pages\Connections\Index.cshtml" />
      <AdditionalFiles Include="Pages\Dialogue\Index.cshtml" />
      <AdditionalFiles Include="Pages\Messages\Index.cshtml" />
      <AdditionalFiles Include="Pages\Pilot\Index.cshtml" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="Pages\Dashboard\Connections\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\Dialogue\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\Messages\Index.cshtml" />
      <_ContentIncludedByDefault Remove="Pages\Dashboard\Pilot\Index.cshtml" />
    </ItemGroup>

</Project>
